### ISSUE TITLE
question about safe heaps post

### ISSUE THREAD

**Issue by bttmly** [husobee/husobee.github.io#2]
https://husobee.github.io/heaps/golang/safe/2016/09/01/safe-heaps-golang.html

With regards to this post, it seems like the another solution to making a heap thread safe would be to use a `sync.Mutex`. Did you evaluate this approach at all, and if so, what led you to prefer the channel-based approach outlined in the post? (I realize this would mean implementing locking in the heap-implementing type used in your application, rather than as a general addition to the heap interface).

Also (not an experienced Go programmer, so forgive me if this is off base) it seems like with a single `heapPushChan` and single `heapPopChan`, you need to be careful you only use these methods on a single heap-implementing type, because if there are multiple heaps, they'll end up sharing the same push/pop channels. Is this the case or no?

**Comment by husobee** [comment]
You are absolutely right that a mutex could be used to provide data structure safety.  And you are completely correct that if you use this design with multiple heaps you will effectively be serializing every heap operation across data structures.

I will update the article to specify this more clearly, and give other options. Thank you for your input.

**Comment by bttmly** [comment]
Thanks for the response!
